### ISSUE TITLE
ProfileStore no longer accessible with Ocp-Apim-Subscription-Key method.

### ISSUE THREAD

**Issue by OllieNees** [davidknipe/InsightFormFieldMapper#1]
## Issue
As per [the Epi docs for this API](https://world.episerver.com/documentation/developer-guides/profile-store/profile-store-api/), Authorization is now handled slightly differently, using a header called "Authorization" with a value of "epi-single KEY".

## Reproduction steps
Simply attempt to use this plugin, data is not successfully added to insights and a 401 exception is raised when accessing the API.

## Proposed solution
In `UpsertInsightProfileActor.cs`, changes lines 117 and 141 to:
`request.AddHeader("Authorization", $"epi-single {_profileStoreConfig.Service.SubscriptionKey}");`

**Comment by awfenemore** [comment]
Can confirm, this works 🤙, Thanks Ollie

**Comment by davidknipe** [comment]
Thanks for noticing this and proposing the solution. v1.1.2 is now available on the Episerver Nuget feed: https://nuget.episerver.com/package/?id=InsightFormFieldMapper
